name: MSGMS CI/CD

# Trigger on push to main or on manual dispatch
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: self-hosted  # Use your self-hosted runner
    env:
      OVERLAY: dev        # Change to stg/prd as needed
      DOCKER_TAG: latest
      MS_NAME: msgms
      GCR_PFX: gcr.io/keystone-466112
      DB_HOST: 127.0.0.1
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.24

      - name: Validate Environment
         working-directory: msgms
         run: make validate-env


      - name: Show Config
        run: make show-config

      - name: Build Go Binary
        run: make build

      - name: Run Unit Tests
        run: make test

      - name: Build Docker Image
        run: make docker-build

      - name: Build Docker Migration Image
        run: make docker-build-migrate

      # Push Docker images only for non-dev
      - name: Push Docker Images
        if: ${{ env.OVERLAY != 'dev' }}
        run: make docker-push docker-push-migrate

      # Run DB Migrations
      - name: Run DB Migrations
        run: make db-migrate

      # Deploy to Kubernetes
      - name: Deploy to Kubernetes
        run: make deploy
