name: Msgms CI/CD

on:
  workflow_dispatch:  # Manual trigger
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted

    steps:
      # --------------------------
      # Checkout repository
      # --------------------------
      - name: Checkout repository
        uses: actions/checkout@v4

      # --------------------------
      # Validate environment
      # --------------------------
      - name: Validate environment
        run: make validate-env

      # --------------------------
      # Install Go dependencies
      # --------------------------
      - name: Install Go dependencies
        run: make deps

      # --------------------------
      # Build Go binary
      # --------------------------
      - name: Build Go binary
        run: make build

      # --------------------------
      # Run unit tests
      # --------------------------
      - name: Run unit tests
        run: make test

      # --------------------------
      # Build Docker image
      # --------------------------
      - name: Build Docker image (dev overlay)
        run: make docker-build OVERLAY=dev

      # --------------------------
      # Docker Hub login (main branch only)
      # --------------------------
      - name: Log in to Docker Hub
        if: ${{ github.ref == 'refs/heads/main' }}
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u your-dockerhub-username --password-stdin

      # --------------------------
      # Push Docker image (stg overlay)
      # --------------------------
      - name: Push Docker image
        if: ${{ github.ref == 'refs/heads/main' }}
        run: make docker-push OVERLAY=stg


