name: Msgms CI/CD

on:
  workflow_dispatch:   # manual trigger
  push:
    branches:
      - main           # trigger on push to main

jobs:
  build:
    runs-on: self-hosted   # use your self-hosted runner

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Install dependencies
        working-directory: ./msgms   # 👈 Run inside msgms folder
        run: go mod tidy

      - name: Build Go binary
        working-directory: ./msgms
        run: go build -o bin/msgms ./...

      - name: Run unit tests
        working-directory: ./msgms
        run: go test ./... -v

      - name: Build Docker image
        run: docker build -t msgms:latest ./msgms   # 👈 Point Docker build to msgms

      # Push image only if main branch
      - name: Push Docker image
        if: github.ref == 'refs/heads/main'
        run: |
          docker tag msgms:latest your-dockerhub-username/msgms:latest
          docker push your-dockerhub-username/msgms:latest
