name: Msgms CI/CD

on:
  workflow_dispatch:  # Manual trigger
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # --------------------------
      # Environment Validation
      # --------------------------
      - name: Validate environment
        run: make -C msgms validate-env

      # --------------------------
      # Go Dependencies
      # --------------------------
      - name: Install Go dependencies
        run: make -C msgms deps

      # --------------------------
      # Build Go Binary
      # --------------------------
      - name: Build Go binary
        run: make -C msgms build

      # --------------------------
      # Run Unit Tests
      # --------------------------
      - name: Run unit tests
        run: make -C msgms test

      # --------------------------
      # Build Docker Image
      # --------------------------
      - name: Build Docker image (dev overlay)
        run: make -C msgms docker-build OVERLAY=dev

      # --------------------------
      # Docker Hub Login (main branch only)
      # --------------------------
      - name: Log in to Docker Hub
        if: ${{ github.ref == 'refs/heads/main' }}
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u your-dockerhub-username --password-stdin

      # --------------------------
      # Push Docker Image (stg overlay)
      # --------------------------
      - name: Push Docker image
        if: ${{ github.ref == 'refs/heads/main' }}
        run: make -C msgms docker-push OVERLAY=stg

