name: Msgms CI/CD

on:
  workflow_dispatch:  # manual trigger
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Validate environment
        run: make validate-env   # validates Go, Docker, kubectl, migrate

      - name: Install Go dependencies
        run: make deps          # ensure your Makefile has:
                                # deps:
                                #     cd msgms && go mod tidy

      - name: Build Go binary
        run: make build          # builds Go binary to bin/$(BINARY_NAME)

      - name: Run unit tests
        run: make test           # runs tests under ./tests

      - name: Build Docker image
        run: make docker-build OVERLAY=dev  # dev overlay uses local Docker build

      - name: Log in to Docker Hub (stg/prd only)
        if: ${{ github.ref == 'refs/heads/main' }}
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u your-dockerhub-username --password-stdin

      - name: Push Docker image (stg/prd only)
        if: ${{ github.ref == 'refs/heads/main' }}
        run: make docker-push OVERLAY=stg   # pushes to registry
