name: Msgms CI/CD

on:
  workflow_dispatch:  # manual trigger
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '24.4'   

      - name: Validate environment
        run: make validate-env

      - name: Build Go binary
        run: make build

      - name: Run unit tests
        run: make test

      - name: Build Docker image (dev)
        run: make docker-build OVERLAY=dev

      - name: Log in to Docker Hub (stg/prd only)
        if: ${{ github.ref == 'refs/heads/main' }}
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u your-dockerhub-username --password-stdin

      - name: Push Docker image (stg/prd only)
        if: ${{ github.ref == 'refs/heads/main' }}
        run: make docker-push OVERLAY=stg

